# SPDX-License-Identifier: Apache-2.0
name: graphcap

include:
  - ./apps/servers/inference_bridge/docker-compose.inference.yml
  - ./apps/servers/data_service/docker-compose.dataservice.yml
  - ./packages/datamodel/docker-compose.datamodel.yml
services:

  graphcap_studio:
    container_name: graphcap_ui
    build:
      context: ./apps/frontend/graphcap_studio
      dockerfile: Dockerfile.client.dev
      args:
        - VITE_API_URL=http://localhost:32200/api
    ports:
      - "32200:32200"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:32200"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./.local/logs/graphcap_studio:/workspace/logs
      - ./workspace:/workspace
    develop:
      watch:
        - action: sync
          path: ./apps/frontend/graphcap_studio/src
          target: /app/src
          ignore:
            - "**/.git"
            - "**/node_modules"
            - "**/.DS_Store"
        - action: sync
          path: ./apps/frontend/graphcap_studio/public
          target: /app/public
        - action: sync
          path: ./apps/frontend/graphcap_studio/index.html
          target: /app/index.html
        - action: sync
          path: ./apps/frontend/graphcap_studio/vite.config.ts
          target: /app/vite.config.ts
        - action: sync+restart
          path: ./apps/frontend/graphcap_studio/pnpm-lock.yaml
          target: /app/pnpm-lock.yaml
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://localhost:32100
      - VITE_WORKSPACE_PATH=/workspace/.local
      - VITE_MEDIA_SERVER_URL=http://localhost:32400
      - VITE_DATASETS_PATH=/workspace/datasets
    networks:
      - graphcap
    depends_on:
      - graphcap_media_server

  graphcap_media_server:
    container_name: graphcap_media_server
    build:
      context: ./apps/servers/media_server
      dockerfile: Dockerfile.media_server.dev
    ports:
      - "32400:32400"
    volumes:
      - ./workspace:/workspace
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=32400
      - WORKSPACE_PATH=/workspace
      - DATASETS_PATH=/workspace/datasets
    develop:
      watch:
        - action: sync
          path: ./apps/servers/media_server
          target: /app
          ignore:
            - "**/.git"
            - "**/node_modules"
            - "**/.DS_Store"
        - action: rebuild
          path: ./apps/servers/media_server/package.json
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:32400/health"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - graphcap


volumes:
  graphcap_db:

networks:
  graphcap:
    driver: bridge
