packages:
  - 'apps/frontend/**'
  - 'apps/servers/data_service'
  - 'packages/media-processing'
  - 'packages/datamodel'
  - 'packages/lib'
nodeLinker: hoisted 
# syncInjectedDepsAfterScripts:
# - build

# injectWorkspacePackages: true 