packages:
  - 'apps/frontend/**'
  - 'apps/graphcap-manager'
  - 'apps/servers/data_service'
  - 'packages/media-processing'
  - 'packages/datamodel'
  - 'packages/lib' 
  - 'packages/lib-backend'
  - 'packages/graphcap-ui'
nodeLinker: hoisted 
# syncInjectedDepsAfterScripts:
# - build

# injectWorkspacePackages: true 