version: "3"
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  data: ./servers/data_service/Taskfile.data.yml
  inference: ./src/server/Taskfile.inference.yml
  graphcap: ./src/Taskfile.graphcap.yml
  studio: ./graphcap_studio/Taskfile.studio.yml
tasks:
  dev:
    desc: Start the Docker Compose services in watch mode
    cmds:
      - docker compose --env-file ./workspace/config/.env up --watch --build 

  start:
    desc: Start the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env up -d

  stop:
    desc: Stop the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env down 

  setup:
    desc: Setup the project [TODO: Update to use uv]
    cmds:
      - echo "TODO: Update to current setup workflow"
      # - uv venv --python 3.11
      # - uv pip install -e ".[dev]"
      # - uv pip install -e ./src
      # - uv run python -m src.scripts
      # - task studio:update-deps


