version: "3"
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  data:      ./apps/servers/data_service/Taskfile.data.yml
  inference: ./apps/servers/inference_bridge/server/Taskfile.inference.yml
  studio:    ./apps/frontend/graphcap_studio/Taskfile.studio.yml
  build:     ./deploy/Taskfile.build.yml
tasks:
  dev:
    desc: Start the Docker Compose services in watch mode
    deps: [build:bases]
    cmds:
      - docker compose --env-file ./workspace/config/.env up --watch --build 

  start:
    desc: Start the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env up -d

  stop:
    desc: Stop the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env down 

  setup:
    desc: Setup the project 
    cmds:
      - cmd: cp ./workspace/config/.env.template ./workspace/config/.env
        platforms: [linux, darwin]
      - cmd: cmd /c copy .\\workspace\\config\\.env.template .\\workspace\\config\\.env
        platforms: [windows]



