version: "3"
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  data:      ./servers/data_service/Taskfile.data.yml
  inference: ./servers/inference_bridge/server/Taskfile.inference.yml
  studio:    ./graphcap_studio/Taskfile.studio.yml
  models:    ./servers/model_runners/Task.models.yml
tasks:
  dev:
    desc: Start the Docker Compose services in watch mode
    cmds:
      - docker compose --env-file ./workspace/config/.env up --watch --build 

  start:
    desc: Start the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env up -d

  stop:
    desc: Stop the Docker Compose services
    cmds:
      - docker compose --env-file ./workspace/config/.env down 

  setup:
    desc: Setup the project 
    cmds:
      - cmd: cp ./workspace/config/.env.template ./workspace/config/.env
        platforms: [linux, darwin]
      - cmd: copy .\\workspace\\config\\.env.template .\\workspace\\config\\.env
        platforms: [windows]



