version: "3"
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - uv run python -m build --outdir ./dist 

  lint:
    cmds:
      - uv run ruff check ./src
      - uv run ruff format --check ./src

  test:
    cmds:
      - uv run pytest

  lint:
    desc: Run Ruff linter on all Python files
    cmds:
      - uv run ruff check 

  format:
    desc: Run Ruff formatter on all Python files
    cmds:
      - uv run ruff format 

  check:all:
    desc: Run both linter and formatter in check mode
    cmds:
      - uv run ruff check 
      - uv run ruff format --check 

  fix:all:
    desc: Run both linter and formatter with fixes
    cmds:
      - uv run ruff check --fix ./src
      - uv run ruff format ./src

  dev:
    desc: Start the Docker Compose services in watch mode
    cmds:
      - docker compose up --watch --build 

  stop:
    desc: Stop the Docker Compose services
    cmds:
      - docker compose down 
