# pipeline_run_config.toml

[pipeline]
name = "basic_caption_pipeline"
environment = "development"

[io]
dataset_name = "graphcap_dataset"
input_dir = "/workspace/datasets/os_img"
output_dir = "/workspace/.local/output/v2/providers/ollama"
copy_images = true
sampling_strategy = "increment"
num_samples = 1
sorting_strategy = "name"

[providers.default]
name = "ollama"
provider_config_file = "/workspace/config/provider.config.toml"

[filesystem]
workspace_dir = "/workspace"
dataset_dir = "/workspace/datasets"
output_dir = "/workspace/.local/output/v2/providers/ollama"

[perspective]
global_context = "You are a captioning perspective."

[perspective.enabled]
graph_caption = true


