version: "3"

tasks:
  gcap-base:
    desc: Build the graphcap-base Docker image (Legacy Python base)
    cmds:
      - docker build --progress=plain -t graphcap-base:dev -f deploy/Dockerfile.python.base .

  backend-base:
    desc: Build the graphcap-backend-base Docker image (FROM ts-base + Bun)
    cmds:
      - docker build --progress=plain -t graphcap-backend-base:dev -f deploy/Dockerfile.backend.base .

  bases:
    desc: Build all base images
    cmds:
      - task build:gcap-base
      - task build:backend-base
