[project]
name = "graphcap"
version = "0.1.0"
description = "Graphcap is a tool for capturing and analyzing graph data."
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "openai>=1.66.3",
    "python-dotenv>=1.0.1",
    "termcolor>=2.5.0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
dev = [
    "build>=1.2.2.post1",
    "contxt>=0.1.1",
    "pytest>=8.3.4",
    "ruff>=0.9.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 