name: documentation
on:
  workflow_dispatch:
  push:
    branches: [ "main"]
    paths:
      - 'doc/**'
      - 'packages/graphcap-ui/**'
      - '.github/workflows/documentation.yml'

permissions:
    pages: write
    contents: write
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10.9.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies (Python & Node)
        run: |
          pip install sphinx pydata-sphinx-theme myst_parser
          pnpm install
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Storybook build
        run: |
          pnpm --filter @graphcap/ui build-storybook -o ../../_build/storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
